[build]
  base = "frontend"
  command = "mv ../../package.json ../../package.json.backup && npm install --legacy-peer-deps && npm run build && mv ../../package.json.backup ../../package.json"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 