# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# FORCE NEW DEPLOYMENT - Triggered manually to resolve Azure backend issues

name: Build and deploy Node.js app to Azure Web App - african-fintech-index

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Build backend
        run: |
          cd backend
          rm -rf dist node_modules/.cache
          # First, ensure package-lock.json is in sync
          npm install
          # Then run the build
          npm run build
          # Verify the build output
          echo "=== Build verification ==="
          ls -la dist/
          echo "=== Checking if dist/index.js exists ==="
          if [ -f "dist/index.js" ]; then
            echo "✅ dist/index.js exists"
            echo "=== File size: $(wc -c < dist/index.js) bytes ==="
            echo "=== First 5 lines of dist/index.js ==="
            head -5 dist/index.js
          else
            echo "❌ dist/index.js not found!"
            echo "=== Contents of dist folder ==="
            ls -la dist/
            echo "=== Backend directory contents ==="
            ls -la
            exit 1
          fi

      - name: Prepare deployment package
        run: |
          # Create a deployment directory with backend contents
          mkdir deployment
          
          # Verify dist folder exists and has content
          echo "=== Checking backend/dist contents ==="
          ls -la backend/dist/
          
          # Copy dist contents (with error handling)
          if [ -d "backend/dist" ] && [ "$(ls -A backend/dist)" ]; then
            echo "✅ dist folder exists and has content"
            cp -r backend/dist/* deployment/
          else
            echo "❌ dist folder is missing or empty!"
            echo "=== Backend directory contents ==="
            ls -la backend/
            exit 1
          fi
          
          cp backend/package.json deployment/
          cp backend/package-lock.json deployment/
          
          # Ensure all dependencies are included
          echo "=== Deployment package contents ==="
          ls -la deployment/
          echo "=== Package.json in deployment ==="
          cat deployment/package.json

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: deployment

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'african-fintech-index'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_5F5035005A744F81879BD819CB24B7D3 }}